language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install . --use-mirrors
  - pip install -r tests/requirements/base.txt
script: python run_tests.py --settings=tests.default
after_script:
    - pep8 --count --statistics --exclude=scheduler,locations,ajax ./rapidsms/
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
